[tool.poetry]
name = "jokeapi"
version = "0.2.11"
description = "An API wrapper for Sv443's JokeAPI"
authors = ["leet hakker <leet_haker@cyber-wizard.com>"]
maintainers = ["leet hakker <leet_haker@cyber-wizard.com>"]
readme = "README.md"
homepage = "https://github.com/thenamesweretakenalready/Sv443s-JokeAPI-Python-Wrapper"

[tool.poetry.dependencies]
python = "^3.8"
urllib3 = "^1.26.2"
simplejson = "^3.17.2"
python-dotenv = "^0.15.0"
pytest = "^6.2.1"
flake8 = "^3.8.4"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
mypy = "^0.790"


[build-system]
requires = ["poetry-core>=1.0.0",
    	    "setuptools>=30.3.0,<50",
	    "wheel",
	    "pytest-runner",
	    "setuptools_scm>=3.3.1",
	    ]
build-backend = "poetry.core.masonry.api"
